import mongoose from "mongoose";
import Book from "./models/Book.js";
import dotenv from "dotenv";

dotenv.config();

const books = [
  // Fiction Books
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    description: "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    category: "Fiction",
    subcategory: "Classic",
    publisher: "Scribner",
    publishYear: 1925,
    pages: 180,
    price: 15.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/footer/book22.png",
    tags: ["classic", "romance", "american literature"],
    rating: 4.5,
    ratingCount: 450,
    borrowCount: 120,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
    category: "Fiction",
    subcategory: "Classic",
    publisher: "J.B. Lippincott & Co.",
    publishYear: 1960,
    pages: 281,
    price: 12.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_8257991.jpg",
    tags: ["classic", "southern gothic", "legal drama"],
    rating: 4.8,
    ratingCount: 520,
    borrowCount: 200,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    description: "A dystopian social science fiction novel that examines the consequences of totalitarianism.",
    category: "Fiction",
    subcategory: "Science Fiction",
    publisher: "Secker & Warburg",
    publishYear: 1949,
    pages: 328,
    price: 14.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/footer/book22.png",
    tags: ["dystopian", "science fiction", "political fiction"],
    rating: 4.7,
    ratingCount: 600,
    borrowCount: 180,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  // Non-Fiction Books
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    description: "Explores the history of humankind from the evolution of archaic human species to the twenty-first century.",
    category: "Non-Fiction",
    subcategory: "History",
    publisher: "Harvill Secker",
    publishYear: 2011,
    pages: 443,
    price: 18.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_8634250.jpg",
    tags: ["history", "anthropology", "science"],
    rating: 4.6,
    ratingCount: 780,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "9780857197689",
    description: "Timeless lessons on wealth, greed, and happiness doing the same thing.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "Harriman House",
    publishYear: 2020,
    pages: 256,
    price: 16.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/footer/book22.png",
    tags: ["finance", "psychology", "self-help"],
    rating: 4.5,
    ratingCount: 420,
    borrowCount: 280,
    badge: "Trending",
    isFeatured: true,
    isNewRelease: true,
    status: "available"
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    description: "An easy & proven way to build good habits & break bad ones.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "Avery",
    publishYear: 2018,
    pages: 320,
    price: 17.99,
    totalCopies: 12,
    availableCopies: 8,
    coverImage: "/images/footer/book22.png",
    tags: ["habits", "productivity", "self-improvement"],
    rating: 4.8,
    ratingCount: 900,
    borrowCount: 450,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  // Science Books
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "9780553380163",
    description: "A landmark volume in science writing by one of the great minds of our time.",
    category: "Science",
    subcategory: "Physics",
    publisher: "Bantam Books",
    publishYear: 1988,
    pages: 256,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/footer/book22.png",
    tags: ["physics", "cosmology", "astrophysics"],
    rating: 4.7,
    ratingCount: 650,
    borrowCount: 300,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    isbn: "9780199291151",
    description: "A classic work in the science of evolution and genetics.",
    category: "Science",
    subcategory: "Biology",
    publisher: "Oxford University Press",
    publishYear: 1976,
    pages: 360,
    price: 16.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/footer/book22.png",
    tags: ["biology", "evolution", "genetics"],
    rating: 4.4,
    ratingCount: 380,
    borrowCount: 150,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  // History Books
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    isbn: "9780393317558",
    description: "The fates of human societies in a compelling and accessible way.",
    category: "History",
    subcategory: "World History",
    publisher: "W.W. Norton & Company",
    publishYear: 1997,
    pages: 480,
    price: 18.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/footer/book22.png",
    tags: ["history", "anthropology", "geography"],
    rating: 4.3,
    ratingCount: 520,
    borrowCount: 200,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  // Biography Books
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    isbn: "9780553296983",
    description: "The diary of a young Jewish girl hiding during the Nazi occupation.",
    category: "Biography",
    subcategory: "Memoir",
    publisher: "Contact Publishing",
    publishYear: 1947,
    pages: 283,
    price: 13.99,
    totalCopies: 8,
    availableCopies: 6,
    coverImage: "/images/footer/book22.png",
    tags: ["holocaust", "world war ii", "memoir"],
    rating: 4.9,
    ratingCount: 800,
    borrowCount: 400,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  // Children Books
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    description: "The mystical story of Santiago, a young shepherd from Andalusia.",
    category: "Children",
    subcategory: "Fable",
    publisher: "HarperTorch",
    publishYear: 1988,
    pages: 163,
    price: 11.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_6976035.jpg",
    tags: ["fable", "adventure", "inspirational"],
    rating: 4.6,
    ratingCount: 750,
    borrowCount: 320,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Matilda",
    author: "Roald Dahl",
    isbn: "9780142410370",
    description: "A brilliant and sensitive child who finds her life changed by literature.",
    category: "Children",
    subcategory: "Fiction",
    publisher: "Jonathan Cape",
    publishYear: 1988,
    pages: 240,
    price: 10.99,
    totalCopies: 9,
    availableCopies: 6,
    coverImage: "/images/footer/book22.png",
    tags: ["children", "magic", "school"],
    rating: 4.7,
    ratingCount: 450,
    borrowCount: 280,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  // Business Books
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "9780307887894",
    description: "How today's entrepreneurs use continuous innovation to create radically successful businesses.",
    category: "Business",
    subcategory: "Entrepreneurship",
    publisher: "Crown Business",
    publishYear: 2011,
    pages: 320,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/footer/book22.png",
    tags: ["startup", "entrepreneurship", "innovation"],
    rating: 4.4,
    ratingCount: 380,
    borrowCount: 180,
    badge: "Trending",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  // Technology Books
  {
    title: "Deep Work",
    author: "Cal Newport",
    isbn: "9781455586691",
    description: "Rules for focused success in a distracted world.",
    category: "Technology",
    subcategory: "Productivity",
    publisher: "Grand Central Publishing",
    publishYear: 2016,
    pages: 296,
    price: 17.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/footer/book22.png",
    tags: ["productivity", "focus", "technology"],
    rating: 4.6,
    ratingCount: 500,
    borrowCount: 250,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: true,
    status: "available"
  },
  // Academic Books
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "9780374533557",
    description: "A revolutionary exploration of the two systems that drive the way we think.",
    category: "Academic",
    subcategory: "Psychology",
    publisher: "Farrar, Straus and Giroux",
    publishYear: 2011,
    pages: 499,
    price: 20.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/footer/book22.png",
    tags: ["psychology", "cognition", "decision making"],
    rating: 4.5,
    ratingCount: 600,
    borrowCount: 220,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  }
];

async function seedBooks() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB");

    // Clear existing books
    await Book.deleteMany({});
    console.log("Cleared existing books");

    // Insert new books
    const result = await Book.insertMany(books);
    console.log(`✅ Successfully seeded ${result.length} books!`);

    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding books:", error.message);
    process.exit(1);
  }
}

seedBooks();
