import mongoose from "mongoose";
import Book from "./models/Book.js";
import dotenv from "dotenv";

dotenv.config({ path: "./.env" });

const books = [
  // ==================== FICTION BOOKS ====================
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    isbn: "9780743273565",
    description: "A story of the mysteriously wealthy Jay Gatsby and his love for Daisy Buchanan.",
    category: "Fiction",
    subcategory: "Classic",
    publisher: "Scribner",
    publishYear: 1925,
    pages: 180,
    price: 15.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_8257991.jpg",
    tags: ["classic", "romance", "american literature"],
    rating: 4.5,
    ratingCount: 450,
    borrowCount: 120,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    isbn: "9780061120084",
    description: "The unforgettable novel of childhood in a sleepy Southern town.",
    category: "Fiction",
    subcategory: "Classic",
    publisher: "J.B. Lippincott",
    publishYear: 1960,
    pages: 281,
    price: 12.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_8257991.jpg",
    tags: ["classic", "southern gothic", "legal drama"],
    rating: 4.8,
    ratingCount: 520,
    borrowCount: 200,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "1984",
    author: "George Orwell",
    isbn: "9780451524935",
    description: "A dystopian novel examining totalitarianism and surveillance.",
    category: "Fiction",
    subcategory: "Science Fiction",
    publisher: "Secker & Warburg",
    publishYear: 1949,
    pages: 328,
    price: 14.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_490106.jpg",
    tags: ["dystopian", "science fiction", "political"],
    rating: 4.7,
    ratingCount: 600,
    borrowCount: 180,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    isbn: "9780062315007",
    description: "The mystical story of Santiago, a young shepherd from Andalusia.",
    category: "Fiction",
    subcategory: "Philosophical Fiction",
    publisher: "HarperTorch",
    publishYear: 1988,
    pages: 163,
    price: 11.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_6976035.jpg",
    tags: ["fable", "adventure", "inspirational"],
    rating: 4.6,
    ratingCount: 750,
    borrowCount: 320,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    isbn: "9781503290563",
    description: "The story of Elizabeth Bennet and Mr. Darcy in Regency England.",
    category: "Fiction",
    subcategory: "Romance",
    publisher: "T. Egerton",
    publishYear: 1813,
    pages: 432,
    price: 9.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_368541.jpg",
    tags: ["romance", "classic", "british literature"],
    rating: 4.6,
    ratingCount: 680,
    borrowCount: 290,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    isbn: "9780316769488",
    description: "The story of teenage alienation and rebellion.",
    category: "Fiction",
    subcategory: "Coming-of-Age",
    publisher: "Little, Brown and Company",
    publishYear: 1951,
    pages: 234,
    price: 13.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["coming-of-age", "classic", "teenager"],
    rating: 4.3,
    ratingCount: 550,
    borrowCount: 240,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    isbn: "9780060850524",
    description: "A dystopian vision of a future society driven by technology.",
    category: "Fiction",
    subcategory: "Science Fiction",
    publisher: "Chatto & Windus",
    publishYear: 1932,
    pages: 311,
    price: 14.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_5269972.jpg",
    tags: ["dystopian", "science fiction", "future society"],
    rating: 4.5,
    ratingCount: 480,
    borrowCount: 200,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    isbn: "9780141439556",
    description: "A tale of passion and revenge on the Yorkshire moors.",
    category: "Fiction",
    subcategory: "Classic",
    publisher: "Thomas Cautley Newby",
    publishYear: 1847,
    pages: 464,
    price: 11.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_12818862.jpg",
    tags: ["classic", "gothic", "romance"],
    rating: 4.4,
    ratingCount: 420,
    borrowCount: 180,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    isbn: "9780618640157",
    description: "The epic fantasy trilogy of Middle-earth.",
    category: "Fiction",
    subcategory: "Fantasy",
    publisher: "Allen & Unwin",
    publishYear: 1954,
    pages: 1178,
    price: 24.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["fantasy", "adventure", "epic"],
    rating: 4.9,
    ratingCount: 850,
    borrowCount: 400,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    isbn: "9780747532743",
    description: "The boy wizard begins his magical journey.",
    category: "Fiction",
    subcategory: "Fantasy",
    publisher: "Bloomsbury",
    publishYear: 1997,
    pages: 223,
    price: 18.99,
    totalCopies: 12,
    availableCopies: 8,
    coverImage: "/images/books/book_8271954.jpg",
    tags: ["fantasy", "magic", "young adult"],
    rating: 4.8,
    ratingCount: 920,
    borrowCount: 500,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    isbn: "9780547928227",
    description: "Bilbo Baggins' unexpected adventure.",
    category: "Fiction",
    subcategory: "Fantasy",
    publisher: "Allen & Unwin",
    publishYear: 1937,
    pages: 310,
    price: 16.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_7153600.jpg",
    tags: ["fantasy", "adventure", "classic"],
    rating: 4.7,
    ratingCount: 780,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    isbn: "9781451673319",
    description: "A fireman who burns books in a censorship-driven society.",
    category: "Fiction",
    subcategory: "Science Fiction",
    publisher: "Ballantine Books",
    publishYear: 1953,
    pages: 249,
    price: 13.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_5951738.jpg",
    tags: ["dystopian", "science fiction", "censorship"],
    rating: 4.6,
    ratingCount: 520,
    borrowCount: 230,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    isbn: "9780141439570",
    description: "A man whose portrait ages while he remains young.",
    category: "Fiction",
    subcategory: "Gothic Fiction",
    publisher: "Lippincott's Monthly Magazine",
    publishYear: 1890,
    pages: 254,
    price: 12.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_14314858.jpg",
    tags: ["gothic", "philosophy", "classic"],
    rating: 4.5,
    ratingCount: 450,
    borrowCount: 190,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    isbn: "9780679734505",
    description: "A psychological drama about a poverty-stricken student.",
    category: "Fiction",
    subcategory: "Psychological Fiction",
    publisher: "The Russian Messenger",
    publishYear: 1866,
    pages: 671,
    price: 14.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_8443662.jpg",
    tags: ["psychological", "classic", "russian literature"],
    rating: 4.6,
    ratingCount: 480,
    borrowCount: 210,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    isbn: "9780140449266",
    description: "A tale of betrayal, imprisonment, and revenge.",
    category: "Fiction",
    subcategory: "Adventure",
    publisher: "Pétion",
    publishYear: 1844,
    pages: 1276,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_12717083.jpg",
    tags: ["adventure", "revenge", "classic"],
    rating: 4.7,
    ratingCount: 550,
    borrowCount: 250,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    isbn: "9781503211919",
    description: "A girl falls through a rabbit hole into a fantasy world.",
    category: "Fiction",
    subcategory: "Children's Literature",
    publisher: "Macmillan",
    publishYear: 1865,
    pages: 192,
    price: 10.99,
    totalCopies: 8,
    availableCopies: 6,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["children", "fantasy", "classic"],
    rating: 4.8,
    ratingCount: 650,
    borrowCount: 300,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    isbn: "9780156012195",
    description: "A poetic tale of a young prince visiting Earth.",
    category: "Fiction",
    subcategory: "Fable",
    publisher: "Reynal & Hitchcock",
    publishYear: 1943,
    pages: 96,
    price: 9.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_5634516.jpg",
    tags: ["fable", "children", "philosophy"],
    rating: 4.9,
    ratingCount: 800,
    borrowCount: 380,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    isbn: "9780060934347",
    description: "The adventures of a noble who reads too many chivalric romances.",
    category: "Fiction",
    subcategory: "Satire",
    publisher: "Francisco de Robles",
    publishYear: 1605,
    pages: 1072,
    price: 16.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_8157718.jpg",
    tags: ["satire", "classic", "adventure"],
    rating: 4.5,
    ratingCount: 420,
    borrowCount: 180,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    isbn: "9780141439471",
    description: "A scientist creates a grotesque creature in an unorthodox experiment.",
    category: "Fiction",
    subcategory: "Gothic Fiction",
    publisher: "Lackington, Hughes, Harding, Mavor & Jones",
    publishYear: 1818,
    pages: 280,
    price: 13.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_490106.jpg",
    tags: ["gothic", "science fiction", "horror"],
    rating: 4.7,
    ratingCount: 500,
    borrowCount: 220,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== NON-FICTION BOOKS ====================
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    isbn: "9780062316097",
    description: "Explores human history from evolution to the 21st century.",
    category: "Non-Fiction",
    subcategory: "History",
    publisher: "Harvill Secker",
    publishYear: 2011,
    pages: 443,
    price: 18.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_8634250.jpg",
    tags: ["history", "anthropology", "science"],
    rating: 4.6,
    ratingCount: 780,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    isbn: "9780735211292",
    description: "An easy and proven way to build good habits and break bad ones.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "Avery",
    publishYear: 2018,
    pages: 320,
    price: 17.99,
    totalCopies: 12,
    availableCopies: 8,
    coverImage: "/images/books/book_9829028.jpg",
    tags: ["habits", "productivity", "self-improvement"],
    rating: 4.8,
    ratingCount: 900,
    borrowCount: 450,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    isbn: "9780857197689",
    description: "Timeless lessons on wealth, greed, and happiness.",
    category: "Non-Fiction",
    subcategory: "Finance",
    publisher: "Harriman House",
    publishYear: 2020,
    pages: 256,
    price: 16.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_968312.jpg",
    tags: ["finance", "psychology", "self-help"],
    rating: 4.5,
    ratingCount: 420,
    borrowCount: 280,
    badge: "Trending",
    isFeatured: true,
    isNewRelease: true,
    status: "available"
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    isbn: "9780374533557",
    description: "Explores the two systems that drive the way we think.",
    category: "Non-Fiction",
    subcategory: "Psychology",
    publisher: "Farrar, Straus and Giroux",
    publishYear: 2011,
    pages: 499,
    price: 20.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_5634516.jpg",
    tags: ["psychology", "cognition", "decision making"],
    rating: 4.5,
    ratingCount: 600,
    borrowCount: 220,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    isbn: "9781577314806",
    description: "A guide to spiritual enlightenment and living in the present.",
    category: "Non-Fiction",
    subcategory: "Spirituality",
    publisher: "Namaste Publishing",
    publishYear: 1997,
    pages: 236,
    price: 15.99,
    totalCopies: 9,
    availableCopies: 6,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["spirituality", "mindfulness", "self-help"],
    rating: 4.7,
    ratingCount: 680,
    borrowCount: 320,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Educated",
    author: "Tara Westover",
    isbn: "9780399590504",
    description: "A memoir about a girl who leaves her survivalist family for education.",
    category: "Non-Fiction",
    subcategory: "Memoir",
    publisher: "Random House",
    publishYear: 2018,
    pages: 352,
    price: 16.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_12746894.jpg",
    tags: ["memoir", "education", "inspirational"],
    rating: 4.8,
    ratingCount: 750,
    borrowCount: 380,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    isbn: "9781982137274",
    description: "A powerful lesson in personal change.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "Free Press",
    publishYear: 1989,
    pages: 432,
    price: 18.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_9829028.jpg",
    tags: ["self-help", "leadership", "productivity"],
    rating: 4.6,
    ratingCount: 850,
    borrowCount: 400,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    isbn: "9781612680194",
    description: "What the rich teach their kids about money.",
    category: "Non-Fiction",
    subcategory: "Finance",
    publisher: "Warner Books",
    publishYear: 1997,
    pages: 336,
    price: 14.99,
    totalCopies: 11,
    availableCopies: 8,
    coverImage: "/images/books/book_968312.jpg",
    tags: ["finance", "wealth", "investing"],
    rating: 4.4,
    ratingCount: 720,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    isbn: "9780062457715",
    description: "A counterintuitive approach to living a good life.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "HarperCollins",
    publishYear: 2016,
    pages: 224,
    price: 15.99,
    totalCopies: 9,
    availableCopies: 6,
    coverImage: "/images/books/book_12746894.jpg",
    tags: ["self-help", "philosophy", "humor"],
    rating: 4.3,
    ratingCount: 680,
    borrowCount: 320,
    badge: "Trending",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    isbn: "9781455586691",
    description: "Rules for focused success in a distracted world.",
    category: "Non-Fiction",
    subcategory: "Productivity",
    publisher: "Grand Central Publishing",
    publishYear: 2016,
    pages: 296,
    price: 17.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_5951738.jpg",
    tags: ["productivity", "focus", "technology"],
    rating: 4.6,
    ratingCount: 500,
    borrowCount: 250,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: true,
    status: "available"
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    isbn: "9780807014295",
    description: "A psychiatrist's experience in Nazi death camps and logotherapy.",
    category: "Non-Fiction",
    subcategory: "Psychology",
    publisher: "Beacon Press",
    publishYear: 1946,
    pages: 165,
    price: 12.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_8443662.jpg",
    tags: ["psychology", "holocaust", "meaning"],
    rating: 4.8,
    ratingCount: 700,
    borrowCount: 340,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The 4-Hour Workweek",
    author: "Timothy Ferriss",
    isbn: "9780307465351",
    description: "Escape 9-5, live anywhere, and join the new rich.",
    category: "Non-Fiction",
    subcategory: "Business",
    publisher: "Crown Publishing",
    publishYear: 2007,
    pages: 396,
    price: 18.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["business", "lifestyle", "entrepreneurship"],
    rating: 4.4,
    ratingCount: 580,
    borrowCount: 280,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    isbn: "9780671027032",
    description: "Timeless advice on building relationships and influencing others.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "Simon & Schuster",
    publishYear: 1936,
    pages: 288,
    price: 13.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_968312.jpg",
    tags: ["self-help", "relationships", "communication"],
    rating: 4.7,
    ratingCount: 800,
    borrowCount: 380,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Life-Changing Magic of Tidying Up",
    author: "Marie Kondo",
    isbn: "9781607747307",
    description: "The Japanese art of decluttering and organizing.",
    category: "Non-Fiction",
    subcategory: "Self-Help",
    publisher: "Ten Speed Press",
    publishYear: 2011,
    pages: 224,
    price: 14.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_12746894.jpg",
    tags: ["organization", "minimalism", "self-help"],
    rating: 4.3,
    ratingCount: 520,
    borrowCount: 260,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    isbn: "9780812964855",
    description: "Private reflections of the Roman emperor on Stoic philosophy.",
    category: "Non-Fiction",
    subcategory: "Philosophy",
    publisher: "Modern Library",
    publishYear: 180,
    pages: 254,
    price: 11.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_5634516.jpg",
    tags: ["philosophy", "stoicism", "classic"],
    rating: 4.7,
    ratingCount: 600,
    borrowCount: 290,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    isbn: "9780143127741",
    description: "Brain, mind, and body in the healing of trauma.",
    category: "Non-Fiction",
    subcategory: "Psychology",
    publisher: "Viking",
    publishYear: 2014,
    pages: 464,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_8443662.jpg",
    tags: ["psychology", "trauma", "healing"],
    rating: 4.8,
    ratingCount: 650,
    borrowCount: 310,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Quiet: The Power of Introverts",
    author: "Susan Cain",
    isbn: "9780307352156",
    description: "A celebration of introversion in a world that cannot stop talking.",
    category: "Non-Fiction",
    subcategory: "Psychology",
    publisher: "Crown Publishing",
    publishYear: 2012,
    pages: 352,
    price: 16.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_12746894.jpg",
    tags: ["psychology", "personality", "self-help"],
    rating: 4.5,
    ratingCount: 580,
    borrowCount: 270,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== SCIENCE BOOKS ====================
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    isbn: "9780553380163",
    description: "A landmark book in science writing by a great mind.",
    category: "Science",
    subcategory: "Physics",
    publisher: "Bantam Books",
    publishYear: 1988,
    pages: 256,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_368541.jpg",
    tags: ["physics", "cosmology", "astrophysics"],
    rating: 4.7,
    ratingCount: 650,
    borrowCount: 300,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    isbn: "9780199291151",
    description: "A classic work in the science of evolution and genetics.",
    category: "Science",
    subcategory: "Biology",
    publisher: "Oxford University Press",
    publishYear: 1976,
    pages: 360,
    price: 16.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_490106.jpg",
    tags: ["biology", "evolution", "genetics"],
    rating: 4.4,
    ratingCount: 380,
    borrowCount: 150,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Cosmos",
    author: "Carl Sagan",
    isbn: "9780345331359",
    description: "A personal voyage through the universe.",
    category: "Science",
    subcategory: "Astronomy",
    publisher: "Random House",
    publishYear: 1980,
    pages: 396,
    price: 18.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_5269972.jpg",
    tags: ["astronomy", "space", "universe"],
    rating: 4.8,
    ratingCount: 580,
    borrowCount: 280,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Elegant Universe",
    author: "Brian Greene",
    isbn: "9780393046885",
    description: "Superstrings, hidden dimensions, and the quest for the ultimate theory.",
    category: "Science",
    subcategory: "Physics",
    publisher: "W.W. Norton",
    publishYear: 1999,
    pages: 448,
    price: 19.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_368541.jpg",
    tags: ["physics", "string theory", "cosmology"],
    rating: 4.5,
    ratingCount: 420,
    borrowCount: 180,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Gene: An Intimate History",
    author: "Siddhartha Mukherjee",
    isbn: "9781476733500",
    description: "The story of the gene and genetic research.",
    category: "Science",
    subcategory: "Biology",
    publisher: "Scribner",
    publishYear: 2016,
    pages: 592,
    price: 21.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_8634250.jpg",
    tags: ["biology", "genetics", "medical"],
    rating: 4.7,
    ratingCount: 520,
    borrowCount: 240,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Astrophysics for People in a Hurry",
    author: "Neil deGrasse Tyson",
    isbn: "9780393609394",
    description: "The essential universe in bite-sized chapters.",
    category: "Science",
    subcategory: "Astronomy",
    publisher: "W.W. Norton",
    publishYear: 2017,
    pages: 144,
    price: 14.99,
    totalCopies: 8,
    availableCopies: 6,
    coverImage: "/images/books/book_5269972.jpg",
    tags: ["astronomy", "space", "accessible science"],
    rating: 4.6,
    ratingCount: 680,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: true,
    status: "available"
  },
  {
    title: "The Immortal Life of Henrieta Lacks",
    author: "Rebecca Skloot",
    isbn: "9781400052172",
    description: "The story behind the immortal cell line HeLa.",
    category: "Science",
    subcategory: "Biology",
    publisher: "Crown Publishing",
    publishYear: 2010,
    pages: 384,
    price: 16.99,
    totalCopies: 7,
    availableCopies: 5,
    coverImage: "/images/books/book_8634250.jpg",
    tags: ["biology", "medical ethics", "biography"],
    rating: 4.7,
    ratingCount: 750,
    borrowCount: 380,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "A Short History of Nearly Everything",
    author: "Bill Bryson",
    isbn: "9780767908184",
    description: "The story of science and how we got where we are today.",
    category: "Science",
    subcategory: "General Science",
    publisher: "Broadway Books",
    publishYear: 2003,
    pages: 544,
    price: 17.99,
    totalCopies: 9,
    availableCopies: 6,
    coverImage: "/images/books/book_368541.jpg",
    tags: ["science", "history", "accessible"],
    rating: 4.5,
    ratingCount: 620,
    borrowCount: 290,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Double Helix",
    author: "James Watson",
    isbn: "9780743216302",
    description: "The discovery of the structure of DNA.",
    category: "Science",
    subcategory: "Biology",
    publisher: "Atheneum",
    publishYear: 1968,
    pages: 226,
    price: 15.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_490106.jpg",
    tags: ["biology", "dna", "discovery"],
    rating: 4.3,
    ratingCount: 380,
    borrowCount: 160,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Silent Spring",
    author: "Rachel Carson",
    isbn: "9780618249063",
    description: "The book that launched the environmental movement.",
    category: "Science",
    subcategory: "Environmental Science",
    publisher: "Houghton Mifflin",
    publishYear: 1962,
    pages: 368,
    price: 14.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_5269972.jpg",
    tags: ["environment", "pesticides", "ecology"],
    rating: 4.8,
    ratingCount: 520,
    borrowCount: 250,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== CHILDREN'S BOOKS ====================
  {
    title: "Matilda",
    author: "Roald Dahl",
    isbn: "9780142410370",
    description: "A brilliant child finds her life changed by literature.",
    category: "Children",
    subcategory: "Fiction",
    publisher: "Jonathan Cape",
    publishYear: 1988,
    pages: 240,
    price: 10.99,
    totalCopies: 9,
    availableCopies: 6,
    coverImage: "/images/books/book_5259972.jpg",
    tags: ["children", "magic", "school"],
    rating: 4.7,
    ratingCount: 450,
    borrowCount: 280,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Charlie and the Chocolate Factory",
    author: "Roald Dahl",
    isbn: "9780142410318",
    description: "A boy wins a golden ticket to a chocolate factory.",
    category: "Children",
    subcategory: "Fiction",
    publisher: "Alfred A. Knopf",
    publishYear: 1964,
    pages: 192,
    price: 10.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_5259972.jpg",
    tags: ["children", "candy", "adventure"],
    rating: 4.8,
    ratingCount: 680,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Where the Wild Things Are",
    author: "Maurice Sendak",
    isbn: "9780060254926",
    description: "A boy sails to an island of wild creatures.",
    category: "Children",
    subcategory: "Picture Book",
    publisher: "Harper & Row",
    publishYear: 1963,
    pages: 48,
    price: 9.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["children", "monsters", "imagination"],
    rating: 4.9,
    ratingCount: 520,
    borrowCount: 300,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Giving Tree",
    author: "Shel Silverstein",
    isbn: "9780060256654",
    description: "A tree gives everything to a boy she loves.",
    category: "Children",
    subcategory: "Picture Book",
    publisher: "Harper & Row",
    publishYear: 1964,
    pages: 64,
    price: 9.99,
    totalCopies: 11,
    availableCopies: 8,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["children", "giving", "nature"],
    rating: 4.8,
    ratingCount: 750,
    borrowCount: 400,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Green Eggs and Ham",
    author: "Dr. Seuss",
    isbn: "9780394800165",
    description: "Sam-I-Am tries to convince someone to eat green eggs.",
    category: "Children",
    subcategory: "Beginner Books",
    publisher: "Random House",
    publishYear: 1960,
    pages: 72,
    price: 8.99,
    totalCopies: 12,
    availableCopies: 9,
    coverImage: "/images/books/book_7153600.jpg",
    tags: ["children", "rhyming", "food"],
    rating: 4.7,
    ratingCount: 620,
    borrowCount: 380,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Cat in the Hat",
    author: "Dr. Seuss",
    isbn: "9780394800011",
    description: "A cat visits two children on a rainy day.",
    category: "Children",
    subcategory: "Beginner Books",
    publisher: "Random House",
    publishYear: 1957,
    pages: 72,
    price: 8.99,
    totalCopies: 10,
    availableCopies: 7,
    coverImage: "/images/books/book_7153600.jpg",
    tags: ["children", "cat", "rainy day"],
    rating: 4.8,
    ratingCount: 580,
    borrowCount: 320,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Goodnight Moon",
    author: "Margaret Wise Brown",
    isbn: "9780064430173",
    description: "A bunny says goodnight to everything in the room.",
    category: "Children",
    subcategory: "Picture Book",
    publisher: "Harper & Brothers",
    publishYear: 1947,
    pages: 32,
    price: 7.99,
    totalCopies: 13,
    availableCopies: 10,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["children", "bedtime", "bunny"],
    rating: 4.9,
    ratingCount: 480,
    borrowCount: 280,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Oh, the Places You'll Go!",
    author: "Dr. Seuss",
    isbn: "9780679805274",
    description: "A celebration of life's journey and possibilities.",
    category: "Children",
    subcategory: "Inspirational",
    publisher: "Random House",
    publishYear: 1990,
    pages: 56,
    price: 9.99,
    totalCopies: 9,
    availableCopies: 6,
    coverImage: "/images/books/book_7153600.jpg",
    tags: ["children", "inspiration", "graduation"],
    rating: 4.8,
    ratingCount: 650,
    borrowCount: 350,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Charlotte's Web",
    author: "E.B. White",
    isbn: "9780064400558",
    description: "A spider saves a pig with words.",
    category: "Children",
    subcategory: "Fiction",
    publisher: "Harper & Brothers",
    publishYear: 1952,
    pages: 192,
    price: 10.99,
    totalCopies: 8,
    availableCopies: 5,
    coverImage: "/images/books/book_5259972.jpg",
    tags: ["children", "spider", "friendship"],
    rating: 4.9,
    ratingCount: 720,
    borrowCount: 380,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    isbn: "9780399226908",
    description: "A caterpillar eats his way to becoming a butterfly.",
    category: "Children",
    subcategory: "Picture Book",
    publisher: "Philomel Books",
    publishYear: 1969,
    pages: 32,
    price: 8.99,
    totalCopies: 11,
    availableCopies: 8,
    coverImage: "/images/books/book_7153600.jpg",
    tags: ["children", "caterpillar", "numbers"],
    rating: 4.8,
    ratingCount: 580,
    borrowCount: 320,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== BUSINESS BOOKS ====================
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    isbn: "9780307887894",
    description: "How entrepreneurs use continuous innovation to create successful businesses.",
    category: "Business",
    subcategory: "Entrepreneurship",
    publisher: "Crown Business",
    publishYear: 2011,
    pages: 320,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["startup", "entrepreneurship", "innovation"],
    rating: 4.4,
    ratingCount: 380,
    borrowCount: 180,
    badge: "Trending",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Good to Great",
    author: "Jim Collins",
    isbn: "9780066620992",
    description: "Why some companies make the leap and others don't.",
    category: "Business",
    subcategory: "Management",
    publisher: "HarperBusiness",
    publishYear: 2001,
    pages: 320,
    price: 18.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["business", "management", "success"],
    rating: 4.6,
    ratingCount: 520,
    borrowCount: 250,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    isbn: "9780062273200",
    description: "Building a business when there are no easy answers.",
    category: "Business",
    subcategory: "Entrepreneurship",
    publisher: "HarperBusiness",
    publishYear: 2014,
    pages: 304,
    price: 19.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["startup", "leadership", "management"],
    rating: 4.5,
    ratingCount: 420,
    borrowCount: 200,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== TECHNOLOGY BOOKS ====================
  {
    title: "The Innovators",
    author: "Walter Isaacson",
    isbn: "9781476708690",
    description: "How a group of inventors created the digital revolution.",
    category: "Technology",
    subcategory: "History",
    publisher: "Simon & Schuster",
    publishYear: 2014,
    pages: 560,
    price: 19.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["technology", "history", "innovation"],
    rating: 4.6,
    ratingCount: 480,
    borrowCount: 220,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    isbn: "9781451648539",
    description: "The biography of Apple's co-founder.",
    category: "Technology",
    subcategory: "Biography",
    publisher: "Simon & Schuster",
    publishYear: 2011,
    pages: 656,
    price: 21.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_12707846.jpg",
    tags: ["biography", "apple", "innovation"],
    rating: 4.7,
    ratingCount: 580,
    borrowCount: 280,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },

  // ==================== BIOGRAPHY BOOKS ====================
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    isbn: "9780553296983",
    description: "The diary of a young Jewish girl hiding during Nazi occupation.",
    category: "Biography",
    subcategory: "Memoir",
    publisher: "Contact Publishing",
    publishYear: 1947,
    pages: 283,
    price: 13.99,
    totalCopies: 8,
    availableCopies: 6,
    coverImage: "/images/books/book_9280435.jpg",
    tags: ["holocaust", "world war ii", "memoir"],
    rating: 4.9,
    ratingCount: 800,
    borrowCount: 400,
    badge: "Popular",
    isFeatured: true,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    isbn: "9780316548182",
    description: "The autobiography of Nelson Mandela.",
    category: "Biography",
    subcategory: "Memoir",
    publisher: "Little, Brown & Company",
    publishYear: 1994,
    pages: 656,
    price: 16.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_12746894.jpg",
    tags: ["biography", "south africa", "politics"],
    rating: 4.8,
    ratingCount: 650,
    borrowCount: 320,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== PHILOSOPHY BOOKS ====================
  {
    title: "Sophie's World",
    author: "Jostein Gaarder",
    isbn: "9780374530716",
    description: "A novel about the history of philosophy.",
    category: "Philosophy",
    subcategory: "Introduction",
    publisher: "Farrar, Straus and Giroux",
    publishYear: 1991,
    pages: 512,
    price: 14.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_5634516.jpg",
    tags: ["philosophy", "history", "novel"],
    rating: 4.5,
    ratingCount: 480,
    borrowCount: 220,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "Thus Spoke Zarathustra",
    author: "Friedrich Nietzsche",
    isbn: "9780140441185",
    description: "A philosophical novel about the Superman.",
    category: "Philosophy",
    subcategory: "Existentialism",
    publisher: "Chemical Publishing",
    publishYear: 1883,
    pages: 352,
    price: 12.99,
    totalCopies: 4,
    availableCopies: 2,
    coverImage: "/images/books/book_5634516.jpg",
    tags: ["philosophy", "existentialism", "classic"],
    rating: 4.4,
    ratingCount: 380,
    borrowCount: 170,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },

  // ==================== ACADEMIC BOOKS ====================
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    isbn: "9780393317558",
    description: "The fates of human societies explained compellingly.",
    category: "Academic",
    subcategory: "History",
    publisher: "W.W. Norton",
    publishYear: 1997,
    pages: 480,
    price: 18.99,
    totalCopies: 6,
    availableCopies: 4,
    coverImage: "/images/books/book_490106.jpg",
    tags: ["history", "anthropology", "geography"],
    rating: 4.3,
    ratingCount: 520,
    borrowCount: 200,
    badge: "Popular",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  },
  {
    title: "The Structure of Scientific Revolutions",
    author: "Thomas S. Kuhn",
    isbn: "9780226458083",
    description: "The classic work on the history of science.",
    category: "Academic",
    subcategory: "Philosophy of Science",
    publisher: "University of Chicago Press",
    publishYear: 1962,
    pages: 212,
    price: 17.99,
    totalCopies: 5,
    availableCopies: 3,
    coverImage: "/images/books/book_368541.jpg",
    tags: ["science", "history", "philosophy"],
    rating: 4.6,
    ratingCount: 480,
    borrowCount: 220,
    badge: "",
    isFeatured: false,
    isNewRelease: false,
    status: "available"
  }
];

async function seedBooks() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB");

    await Book.deleteMany({});
    console.log("Cleared existing books");

    const result = await Book.insertMany(books);
    console.log(`✅ Successfully seeded ${result.length} books!`);

    mongoose.connection.close();
  } catch (error) {
    console.error("Error seeding books:", error.message);
    process.exit(1);
  }
}

seedBooks();
