export default async function seed(req, res) {
  import { connectDB } from "../lib/db.js";
  import User from "../lib/models/User.js";
  import Book from "../lib/models/Book.js";
  import bcrypt from "bcrypt";

  await connectDB();

  const existingBooks = await Book.countDocuments();
  if (existingBooks > 0) {
    console.log("Database already seeded");
    return { message: "Database already seeded" };
  }

  const adminPassword = await bcrypt.hash("admin123", 10);

  const adminUser = await User.create({
    name: "Admin User",
    email: "admin@librivista.com",
    password: adminPassword,
    phone: "+977-01-4256789",
    address: "Kathmandu, Nepal",
    membershipType: "Premium",
    membershipId: "LIB-2026-0001",
    role: "admin",
    isActive: true,
  });

  const userPassword = await bcrypt.hash("user123", 10);

  const regularUser = await User.create({
    name: "Kunjan Bhandari",
    email: "Bhandarikunjan9@gmail.com",
    password: userPassword,
    phone: "+977 9743962189",
    address: "gulmi, satyawati-07-juniya",
    membershipType: "Premium",
    membershipId: "LIB-2024-0892",
    membershipExpiry: new Date("2027-03-15"),
    role: "user",
    isActive: true,
    booksBorrowed: 47,
    booksReturned: 43,
    currentlyBorrowed: 4,
    reservations: 2,
  });

  const books = [
    {
      title: "Atomic Habits",
      author: "James Clear",
      isbn: "9780735211292",
      description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones",
      category: "Self-Help",
      publisher: "Avery",
      publishYear: 2018,
      pages: 320,
      price: 850,
      totalCopies: 15,
      availableCopies: 12,
      coverImage: "/images/footer/book19.svg",
      rating: 4.8,
      ratingCount: 342,
      borrowCount: 342,
      badge: "Trending",
      isFeatured: true,
      tags: ["habits", "self-improvement", "productivity"],
    },
    {
      title: "The Psychology of Money",
      author: "Morgan Housel",
      isbn: "9780857197689",
      description: "Timeless lessons on wealth, greed, and happiness",
      category: "Business",
      publisher: "Harriman House",
      publishYear: 2020,
      pages: 256,
      price: 950,
      totalCopies: 10,
      availableCopies: 7,
      coverImage: "/images/footer/book20.svg",
      rating: 4.7,
      ratingCount: 289,
      borrowCount: 289,
      badge: "Popular",
      isFeatured: true,
      tags: ["finance", "investing", "money"],
    },
    {
      title: "Sapiens: A Brief History of Humankind",
      author: "Yuval Noah Harari",
      isbn: "9780062316097",
      description: "A groundbreaking narrative of humanity's creation and evolution",
      category: "History",
      publisher: "Harper",
      publishYear: 2015,
      pages: 464,
      price: 1100,
      totalCopies: 12,
      availableCopies: 9,
      coverImage: "/images/footer/book21.svg",
      rating: 4.6,
      ratingCount: 256,
      borrowCount: 256,
      badge: "Featured",
      isFeatured: true,
      tags: ["history", "anthropology", "science"],
    },
    {
      title: "The Alchemist",
      author: "Paulo Coelho",
      isbn: "9780062315007",
      description: "A magical story about following your dreams",
      category: "Fiction",
      publisher: "HarperOne",
      publishYear: 1988,
      pages: 197,
      price: 750,
      totalCopies: 20,
      availableCopies: 15,
      coverImage: "/images/footer/book4.svg",
      rating: 4.5,
      ratingCount: 198,
      borrowCount: 198,
      badge: "Popular",
      isFeatured: true,
      tags: ["fiction", "philosophy", "adventure"],
    },
    {
      title: "Deep Work",
      author: "Cal Newport",
      isbn: "9781455586691",
      description: "Rules for Focused Success in a Distracted World",
      category: "Self-Help",
      publisher: "Grand Central Publishing",
      publishYear: 2016,
      pages: 296,
      price: 900,
      totalCopies: 8,
      availableCopies: 5,
      coverImage: "/images/footer/book22.png",
      rating: 4.4,
      ratingCount: 167,
      borrowCount: 167,
      badge: "Trending",
      tags: ["productivity", "focus", "work"],
    },
    {
      title: "Ikigai: The Japanese Secret to a Long and Happy Life",
      author: "Hector Garcia",
      isbn: "9780143130727",
      description: "The Japanese secret to a long and happy life",
      category: "Self-Help",
      publisher: "Penguin Books",
      publishYear: 2017,
      pages: 208,
      price: 800,
      totalCopies: 10,
      availableCopies: 6,
      coverImage: "/images/footer/book21.svg",
      rating: 4.3,
      ratingCount: 145,
      borrowCount: 145,
      badge: "New",
      isNewRelease: true,
      tags: ["lifestyle", "happiness", "japanese"],
    },
    {
      title: "Thinking, Fast and Slow",
      author: "Daniel Kahneman",
      isbn: "9780374533557",
      description: "A groundbreaking tour of the mind that explains the two systems that drive the way we think",
      category: "Science",
      publisher: "Farrar, Straus and Giroux",
      publishYear: 2011,
      pages: 499,
      price: 1200,
      totalCopies: 6,
      availableCopies: 4,
      coverImage: "/images/footer/book22.png",
      rating: 4.6,
      ratingCount: 210,
      borrowCount: 210,
      badge: "Featured",
      isFeatured: true,
      tags: ["psychology", "decision-making", "science"],
    },
    {
      title: "The Lean Startup",
      author: "Eric Ries",
      isbn: "9780307887894",
      description: "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses",
      category: "Business",
      publisher: "Crown Business",
      publishYear: 2011,
      pages: 336,
      price: 1050,
      totalCopies: 8,
      availableCopies: 6,
      coverImage: "/images/footer/book22.png",
      rating: 4.2,
      ratingCount: 178,
      borrowCount: 178,
      tags: ["startup", "entrepreneurship", "business"],
    },
    {
      title: "Dune",
      author: "Frank Herbert",
      isbn: "9780441172719",
      description: "A stunning blend of adventure and mysticism, environmentalism and politics",
      category: "Fiction",
      subcategory: "Fantasy",
      publisher: "Ace",
      publishYear: 1965,
      pages: 688,
      price: 1300,
      totalCopies: 10,
      availableCopies: 8,
      coverImage: "/images/footer/book22.png",
      rating: 4.7,
      ratingCount: 312,
      borrowCount: 312,
      badge: "Popular",
      tags: ["science fiction", "fantasy", "classic"],
    },
    {
      title: "Educated: A Memoir",
      author: "Tara Westover",
      isbn: "9780399590504",
      description: "A memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University",
      category: "Biography",
      publisher: "Random House",
      publishYear: 2018,
      pages: 352,
      price: 950,
      totalCopies: 7,
      availableCopies: 5,
      coverImage: "/images/footer/book22.png",
      rating: 4.5,
      ratingCount: 189,
      borrowCount: 189,
      badge: "New",
      isNewRelease: true,
      tags: ["memoir", "education", "family"],
    },
    {
      title: "The Art of War",
      author: "Sun Tzu",
      isbn: "9781599869773",
      description: "The most influential strategy text in East Asian warfare",
      category: "Philosophy",
      publisher: "Filiquarian Publishing",
      publishYear: 2008,
      pages: 68,
      price: 450,
      totalCopies: 15,
      availableCopies: 12,
      coverImage: "/images/footer/book22.png",
      rating: 4.4,
      ratingCount: 156,
      borrowCount: 156,
      tags: ["strategy", "warfare", "philosophy"],
    },
    {
      title: "Clean Code",
      author: "Robert C. Martin",
      isbn: "9780132350884",
      description: "A Handbook of Agile Software Craftsmanship",
      category: "Technology",
      publisher: "Prentice Hall",
      publishYear: 2008,
      pages: 464,
      price: 1500,
      totalCopies: 5,
      availableCopies: 3,
      coverImage: "/images/footer/book22.png",
      rating: 4.6,
      ratingCount: 234,
      borrowCount: 234,
      badge: "Featured",
      isFeatured: true,
      tags: ["programming", "software", "coding"],
    },
  ];

  await Book.insertMany(books);

  console.log("Database seeded successfully!");
  console.log("Admin: admin@librivista.com / admin123");
  console.log("User: Bhandarikunjan9@gmail.com / user123");

  return { message: "Database seeded successfully" };
}
