import { NextResponse } from "next/server";
import User from "@/lib/models/User.js";
import Book from "@/lib/models/Book.js";
import Borrowing from "@/lib/models/Borrowing.js";
import Reservation from "@/lib/models/Reservation.js";
import bcrypt from "bcryptjs";
import { connectDB } from "@/lib/db.js";

export async function POST() {
  try {
    await connectDB();

    await Promise.all([
      Book.deleteMany({}),
      User.deleteMany({}),
      Borrowing.deleteMany({}),
      Reservation.deleteMany({}),
    ]);

    const adminPassword = await bcrypt.hash("admin123", 10);
    await User.create({
      name: "Admin User",
      email: "admin@librivista.com",
      password: adminPassword,
      phone: "+977-01-4256789",
      address: "Kathmandu, Nepal",
      membershipType: "Premium",
      membershipId: "LIB-2026-0001",
      role: "admin",
      isActive: true,
    });

    const userPassword = await bcrypt.hash("user123", 10);
    const user = await User.create({
      name: "Kunjan Bhandari",
      email: "Bhandarikunjan9@gmail.com",
      password: userPassword,
      phone: "+977 9743962189",
      address: "gulmi, satyawati-07-juniya",
      membershipType: "Premium",
      membershipId: "LIB-2024-0892",
      membershipExpiry: new Date("2027-03-15"),
      role: "user",
      isActive: true,
      booksBorrowed: 47,
      booksReturned: 43,
      currentlyBorrowed: 4,
      reservations: 2,
    });

    const books = [
      {
        title: "Atomic Habits",
        author: "James Clear",
        isbn: "9780735211292",
        description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones. Learn how small changes can transform your life.",
        category: "Self-Help",
        publisher: "Avery",
        publishYear: 2018,
        pages: 320,
        price: 850,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "/images/footer/book19.svg",
        rating: 4.8,
        ratingCount: 342,
        borrowCount: 342,
        badge: "Trending",
        isFeatured: true,
        isNewRelease: false,
        tags: ["habits", "self-improvement", "productivity"],
      },
      {
        title: "The Psychology of Money",
        author: "Morgan Housel",
        isbn: "9780857197689",
        description: "Timeless lessons on wealth, greed, and happiness. Understand how people think about money.",
        category: "Business",
        publisher: "Harriman House",
        publishYear: 2020,
        pages: 256,
        price: 950,
        totalCopies: 10,
        availableCopies: 7,
        coverImage: "/images/footer/book20.svg",
        rating: 4.7,
        ratingCount: 289,
        borrowCount: 289,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["finance", "investing", "money"],
      },
      {
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        isbn: "9780062316097",
        description: "A groundbreaking narrative of humanity's creation and evolution. Explore how Homo sapiens conquered the world.",
        category: "History",
        publisher: "Harper",
        publishYear: 2015,
        pages: 464,
        price: 1100,
        totalCopies: 12,
        availableCopies: 9,
        coverImage: "/images/footer/book21.svg",
        rating: 4.6,
        ratingCount: 256,
        borrowCount: 256,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["history", "anthropology", "science"],
      },
      {
        title: "The Alchemist",
        author: "Paulo Coelho",
        isbn: "9780062315007",
        description: "A magical story about following your dreams. A shepherd boy journeys to Egypt in search of treasure.",
        category: "Fiction",
        publisher: "HarperOne",
        publishYear: 1988,
        pages: 197,
        price: 750,
        totalCopies: 20,
        availableCopies: 15,
        coverImage: "/images/footer/book4.svg",
        rating: 4.5,
        ratingCount: 198,
        borrowCount: 198,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["fiction", "philosophy", "adventure"],
      },
      {
        title: "Deep Work",
        author: "Cal Newport",
        isbn: "9781455586691",
        description: "Rules for Focused Success in a Distracted World. Learn to master focused work.",
        category: "Self-Help",
        publisher: "Grand Central Publishing",
        publishYear: 2016,
        pages: 304,
        price: 800,
        totalCopies: 8,
        availableCopies: 6,
        coverImage: "/images/footer/book5.svg",
        rating: 4.6,
        ratingCount: 245,
        borrowCount: 245,
        badge: "Popular",
        isFeatured: false,
        isNewRelease: false,
        tags: ["productivity", "focus", "work"],
      },
      {
        title: "The Lean Startup",
        author: "Eric Ries",
        isbn: "9780307887894",
        description: "How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Businesses.",
        category: "Business",
        publisher: "Crown Business",
        publishYear: 2011,
        pages: 336,
        price: 900,
        totalCopies: 10,
        availableCopies: 8,
        coverImage: "/images/footer/book6.svg",
        rating: 4.4,
        ratingCount: 312,
        borrowCount: 312,
        badge: "Trending",
        isFeatured: false,
        isNewRelease: false,
        tags: ["startup", "entrepreneurship", "innovation"],
      },
      {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        isbn: "9780061120084",
        description: "A gripping story of racial injustice and childhood innocence in the American South.",
        category: "Fiction",
        publisher: "HarperCollins",
        publishYear: 1960,
        pages: 376,
        price: 700,
        totalCopies: 18,
        availableCopies: 14,
        coverImage: "/images/footer/book7.svg",
        rating: 4.9,
        ratingCount: 421,
        borrowCount: 421,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["classic", "fiction", "american-literature"],
      },
      {
        title: "A Brief History of Time",
        author: "Stephen Hawking",
        isbn: "9780553380163",
        description: "From the Big Bang to Black Holes. Explore the mysteries of the universe.",
        category: "Science",
        publisher: "Bantam",
        publishYear: 1988,
        pages: 256,
        price: 850,
        totalCopies: 12,
        availableCopies: 10,
        coverImage: "/images/footer/book8.svg",
        rating: 4.5,
        ratingCount: 287,
        borrowCount: 287,
        badge: "Featured",
        isFeatured: false,
        isNewRelease: false,
        tags: ["science", "physics", "cosmology"],
      },
      {
        title: "The Diary of a Young Girl",
        author: "Anne Frank",
        isbn: "9780553296983",
        description: "The powerful true story of a young girl hiding from the Nazis during World War II.",
        category: "History",
        publisher: "Bantam",
        publishYear: 1947,
        pages: 283,
        price: 650,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "/images/footer/book9.svg",
        rating: 4.8,
        ratingCount: 356,
        borrowCount: 356,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["history", "biography", "world-war-ii"],
      },
      {
        title: "Thinking, Fast and Slow",
        author: "Daniel Kahneman",
        isbn: "9780374533557",
        description: "How our minds make decisions and the two systems that drive the way we think.",
        category: "Business",
        publisher: "Farrar, Straus and Giroux",
        publishYear: 2011,
        pages: 499,
        price: 1050,
        totalCopies: 9,
        availableCopies: 7,
        coverImage: "/images/footer/book10.svg",
        rating: 4.5,
        ratingCount: 298,
        borrowCount: 298,
        badge: "Popular",
        isFeatured: false,
        isNewRelease: false,
        tags: ["psychology", "decision-making", "behavioral-economics"],
      },
      {
        title: "Mathematics",
        author: "NEP Curriculum Team",
        isbn: "9789937890010",
        description: "Complete Mathematics textbook for Class 10 covering algebra, geometry, trigonometry, statistics, and coordinate geometry as per the Nepal Education Policy curriculum.",
        category: "Academic",
        publisher: "Government of Nepal, Ministry of Education",
        publishYear: 2024,
        pages: 320,
        price: 450,
        totalCopies: 50,
        availableCopies: 42,
        coverImage: "/images/footer/book-math.svg",
        rating: 4.3,
        ratingCount: 156,
        borrowCount: 450,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: true,
        tags: ["math", "class-10", "algebra", "geometry"],
      },
      {
        title: "Chemistry",
        author: "NEP Curriculum Team",
        isbn: "9789937890027",
        description: "Comprehensive Chemistry textbook for Class 10 covering chemical reactions, acids and bases, periodic table, organic chemistry, and laboratory experiments.",
        category: "Science",
        publisher: "Government of Nepal, Ministry of Education",
        publishYear: 2024,
        pages: 280,
        price: 450,
        totalCopies: 45,
        availableCopies: 38,
        coverImage: "/images/footer/book-chemistry.svg",
        rating: 4.2,
        ratingCount: 134,
        borrowCount: 380,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: true,
        tags: ["chemistry", "class-10", "science"],
      },
      {
        title: "Science",
        author: "NEP Curriculum Team",
        isbn: "9789937890034",
        description: "Complete Science textbook for Class 10 covering physics, chemistry, biology, astronomy, and environmental science with practical experiments and diagrams.",
        category: "Science",
        publisher: "Government of Nepal, Ministry of Education",
        publishYear: 2024,
        pages: 350,
        price: 500,
        totalCopies: 55,
        availableCopies: 45,
        coverImage: "/images/footer/book-science.svg",
        rating: 4.4,
        ratingCount: 178,
        borrowCount: 520,
        badge: "Trending",
        isFeatured: true,
        isNewRelease: true,
        tags: ["science", "class-10", "physics", "biology"],
      },
      {
        title: "Muna Madan",
        author: "Lekhnath Paudel",
        isbn: "9789937890041",
        description: "One of the most beloved Nepali poems written in Jhyaure folk meter. It tells the story of Muna and Madan, exploring themes of love, sacrifice, and the hardships of migrant labor. A classic of Nepali literature.",
        category: "Poetry",
        publisher: "Nepal Prakashan",
        publishYear: 2020,
        pages: 120,
        price: 350,
        totalCopies: 30,
        availableCopies: 25,
        coverImage: "/images/footer/book-munamadan.svg",
        rating: 4.9,
        ratingCount: 520,
        borrowCount: 890,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "poetry", "munamadan", "classic"],
      },
      {
        title: "SEE Exam Guide 2081",
        author: "SEE Preparation Board",
        isbn: "9789937890058",
        description: "Complete preparation guide for the Secondary Education Examination (SEE) covering all subjects including Math, Science, English, Nepali, and Social Studies with practice questions, model tests, and past paper solutions.",
        category: "Academic",
        publisher: "Kathmandu Educational Publishers",
        publishYear: 2024,
        pages: 480,
        price: 650,
        totalCopies: 40,
        availableCopies: 32,
        coverImage: "/images/footer/book-see.svg",
        rating: 4.7,
        ratingCount: 345,
        borrowCount: 620,
        badge: "Trending",
        isFeatured: true,
        isNewRelease: true,
        tags: ["SEE", "exam", "class-10", "preparation", "guide"],
      },
    ];

    const createdBooks = await Book.insertMany(books);

    await Borrowing.insertMany([
      {
        user: user._id,
        book: createdBooks[0]._id,
        borrowDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        status: "active",
      },
      {
        user: user._id,
        book: createdBooks[1]._id,
        borrowDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
        dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        returnDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
        status: "returned",
      },
    ]);

    await Reservation.insertMany([
      {
        user: user._id,
        book: createdBooks[2]._id,
        reservedOn: new Date(),
        reserveExpiry: new Date(Date.now() + 48 * 60 * 60 * 1000),
        status: "pending",
        paymentMethod: "eSewa",
        totalPrice: createdBooks[2].price,
        deliveryFee: 100,
        discount: 0,
      },
    ]);

    return NextResponse.json({
      success: true,
      message: "Database seeded successfully with sample data",
      users: {
        admin: { email: "admin@librivista.com", password: "admin123" },
        user: { email: "Bhandarikunjan9@gmail.com", password: "user123" },
      },
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, message: "Seeding failed", error: error.message },
      { status: 500 }
    );
  }
}
