import Book from "../models/Book.js";

export async function seedFromPustakalaya(req, res) {
  try {
    const books = [
      {
        title: "मुनामदन (Muna Madan)",
        author: "लक्ष्मीप्रसाद देवकोटा",
        isbn: "9789937890106",
        description: "महाकवि लक्ष्मीप्रसाद देवकोटाको सर्वाधिक चर्चित खण्डकाव्य मुनामदन बोलचालको सरल नेपाली भाषामा लोकलय, झ्याउरेलाई अँगाली लेखिएको नेपाली साहित्यको पहिलो सच्चा साहित्यिक काव्य हो।",
        category: "Poetry",
        publisher: "साझा प्रकाशन",
        publishYear: 2020,
        pages: 40,
        price: 350,
        totalCopies: 30,
        availableCopies: 25,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/09/30/मनमदन.jpg",
        rating: 4.9,
        ratingCount: 520,
        borrowCount: 890,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "poetry", "munamadan", "devkota", "classic"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/8977bde1-d886-4515-aeb2-4c538d02928e/",
        source: "E-Pustakalaya",
      },
      {
        title: "छन्दको छहरा (Chandako Chahara)",
        author: "रामप्रसाद नेपाल",
        isbn: "9789937890113",
        description: "छन्दका १०१ कविता का पहिलो, दोस्रो र तेस्रो संस्करणबाट मिलेको सफलताले हामीले कविताको यो अर्को सङ्गालो छन्दको छहरा प्रकाशन गर्ने आँट गरेका छौँ।",
        category: "Poetry",
        publisher: "रातो बङ्गला स्कुल",
        publishYear: 2020,
        pages: 120,
        price: 280,
        totalCopies: 25,
        availableCopies: 20,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/5wD28UBUCzFNAtYpcfztlV0e7Gt5G8.jpg",
        rating: 4.6,
        ratingCount: 180,
        borrowCount: 505,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "poetry", "chand", "kavita"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/26a6278e-aa8c-4460-a3e8-d8c03cc1fa47/",
        source: "E-Pustakalaya",
      },
      {
        title: "कति वटा रोटी? (Kati Ota Roti?)",
        author: "श्रीप्रसाद नेपाल",
        isbn: "9789937890120",
        description: "यो किताब भर्खर बाह्रखरी पढिरहेका वा पढिसकेका साना-साना नानीहरूका लागी भनी तयार पारिएको हो। यसमा प्रस्तुत विषय, शैली र प्रस्तुति सहज, मीठो र सरल होस भनेर सकेसम्म मिहिनेत गरिएको छ।",
        category: "Children",
        publisher: "OLE Nepal",
        publishYear: 2020,
        pages: 24,
        price: 150,
        totalCopies: 50,
        availableCopies: 40,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/GtO6XRrbfxJkLyu1jPdtSOSvcPG3P4.jpg",
        rating: 4.8,
        ratingCount: 250,
        borrowCount: 2835,
        badge: "Trending",
        isFeatured: true,
        isNewRelease: true,
        tags: ["nepali", "children", "roti", "early-learning"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/3a0954ed-3e9a-4c3e-83cc-74c2b3093ed3/",
        source: "E-Pustakalaya",
      },
      {
        title: "महाभारतमा के छ? (Mahabharatma Ke Chha?)",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890137",
        description: "आकारमा सानो भएर पनि पूर्वीय ज्ञानको महासाकार मानिने महाभारतका प्रत्येक पर्वको सारांश खिचेर यस महाभारतमा के छ पुस्तकमा त्यसको आशयसमेत सरल र सहजरूपमा प्रष्ट पार्ने प्रयत्न गरिएको छ।",
        category: "Religion",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2023,
        pages: 200,
        price: 450,
        totalCopies: 20,
        availableCopies: 15,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2023/11/02/Mahabharatma_Ke_Chha.png",
        rating: 4.7,
        ratingCount: 310,
        borrowCount: 2078,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: true,
        tags: ["nepali", "mahabharat", "religion", "summary"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/51f33c5b-be41-4cc2-86e4-37977cd5492e/",
        source: "E-Pustakalaya",
      },
      {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        isbn: "9780743273565",
        description: "A portrait of the Jazz Age in all of its decadence and excess. Gatsby's story of the impossibility of recapturing the past has become one of the classics of American literature.",
        category: "Fiction",
        publisher: "Scribner",
        publishYear: 2004,
        pages: 180,
        price: 650,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/K77cJByG5HcBdRuGBIswHEMa9qK55S.gif",
        rating: 4.5,
        ratingCount: 420,
        borrowCount: 850,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["english", "fiction", "classic", "american-literature"],
        language: "English",
        sourceUrl: "https://pustakalaya.org/documents/detail/6147605b-4d6a-4bfd-aad8-786641c0cb75/",
        source: "E-Pustakalaya",
      },
      {
        title: "नोकरी (Nokri - Novel)",
        author: "नारायण ढकाल",
        isbn: "9789937890144",
        description: "प्रस्तुत उपन्यास नोकरी नेपालको २०४६ सालको राजनीतिक परिवर्तनपछिको यथार्थ दस्तावेज हो, जसलाई उहाँले उपन्यासका माध्यमबाट सफलतापूर्वक उतार्नु भएको छ।",
        category: "Fiction",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2022,
        pages: 280,
        price: 550,
        totalCopies: 18,
        availableCopies: 14,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2022/02/03/Web_1920__7.png",
        rating: 4.4,
        ratingCount: 290,
        borrowCount: 4247,
        badge: "Trending",
        isFeatured: true,
        isNewRelease: true,
        tags: ["nepali", "novel", "political", "bureaucracy"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/007108c5-1048-4623-8148-c8187f0cb057/",
        source: "E-Pustakalaya",
      },
      {
        title: "सुम्निमा (Sumnima - Novel)",
        author: "विश्वेश्वरप्रसाद कोइराला",
        isbn: "9789937890151",
        description: "नेपाली वाङ्मयका चर्चित व्यक्तित्व श्री विश्वेश्वरप्रसाद कोइरालाका कृतिहरूमध्ये सुम्निमा कृतिको आफ्नै महत्त्व छ।",
        category: "Fiction",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2020,
        pages: 320,
        price: 500,
        totalCopies: 22,
        availableCopies: 18,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/09/30/समनम_उपनयस.jpg",
        rating: 4.6,
        ratingCount: 380,
        borrowCount: 3287,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "novel", "bp-koirala", "classic"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/9c29f82a-0c30-4ec7-8c9c-816f3885bcc6/",
        source: "E-Pustakalaya",
      },
      {
        title: "स्यालको जुक्ती (Syal ko Jukti)",
        author: "पञ्चकन्या प्रकाशन",
        isbn: "9789937890168",
        description: "यो कथा एउटा चतुर स्याल र निकै भोकाएको बाघको कथा हो। धेरै दिनदेखि खान नपाएको बाघले एउटा खालि गुफा भेटेपछि भित्र गएर त्यस गुफामा बस्ने जनावर कहिले आउला र त्यसलाई खाउँला भनेर कुरेर बस्छ।",
        category: "Children",
        publisher: "OLE Nepal",
        publishYear: 2020,
        pages: 16,
        price: 120,
        totalCopies: 45,
        availableCopies: 35,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/ISzgDZahZ7ntVSoJeUm9wtZcoqCEUZ.jpg",
        rating: 4.7,
        ratingCount: 200,
        borrowCount: 2096,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "children", "folktale", "animals"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/1c78cf70-1b6b-46be-aa81-59e436603f02/",
        source: "E-Pustakalaya",
      },
      {
        title: "School Education Sector Plan 2022/23-2031/32",
        author: "Government of Nepal",
        isbn: "9789937890175",
        description: "For the Nepal School Education Sector 2022/23-2031/32. A comprehensive plan for the development and improvement of school education in Nepal.",
        category: "Academic",
        publisher: "Ministry of Education, Nepal",
        publishYear: 2024,
        pages: 180,
        price: 400,
        totalCopies: 30,
        availableCopies: 25,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2024/06/05/School_Education_Sector_Plan_202223203132.jpg",
        rating: 4.2,
        ratingCount: 85,
        borrowCount: 324,
        badge: "New",
        isFeatured: true,
        isNewRelease: true,
        tags: ["education", "policy", "nepal", "government"],
        language: "English",
        sourceUrl: "https://pustakalaya.org/documents/detail/35e37ead-64ac-43d3-9f27-59f8e93b4b96/",
        source: "E-Pustakalaya",
      },
      {
        title: "छन्दका १०१ कविता",
        author: "रामप्रसाद नेपाल",
        isbn: "9789937890182",
        description: "छन्दका १०१ कविता र छन्दका छहरा यी दुवै किताब रातो बङ्गला स्कुलका साना साना विद्यार्थीहरूका लागि सङ्कलित गरिएका हुन्।",
        category: "Poetry",
        publisher: "रातो बङ्गला स्कुल",
        publishYear: 2020,
        pages: 150,
        price: 300,
        totalCopies: 28,
        availableCopies: 22,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/VkRnNbQWd5bKpG8CKD4t8ulj38Coob.jpg",
        rating: 4.5,
        ratingCount: 195,
        borrowCount: 3578,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "poetry", "chand", "101-kavita"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/035a22b6-ac59-46f6-acc9-109b6958085b/",
        source: "E-Pustakalaya",
      },
      {
        title: "किन डराउनु (Kina Daraunu)",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890199",
        description: "बालबालिकाका लागि तयार पारिएको शिक्षाप्रद पुस्तक।",
        category: "Children",
        publisher: "OLE Nepal",
        publishYear: 2020,
        pages: 20,
        price: 130,
        totalCopies: 40,
        availableCopies: 32,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/06/10/CDC2076BS_Kina_Daraunu.jpg",
        rating: 4.4,
        ratingCount: 150,
        borrowCount: 660,
        badge: "Featured",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "children", "education"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/2d3f963d-16cf-4375-97fe-c63569fa9479/",
        source: "E-Pustakalaya",
      },
      {
        title: "कुन खेल खेल्ने (Kun Khel Khelne)",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890205",
        description: "बालबालिकाका लागि खेलकुद सम्बन्धी जानकारी दिने पुस्तक।",
        category: "Children",
        publisher: "OLE Nepal",
        publishYear: 2020,
        pages: 24,
        price: 140,
        totalCopies: 35,
        availableCopies: 28,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/05/01/कन_खल_खलन.jpg",
        rating: 4.3,
        ratingCount: 120,
        borrowCount: 462,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "children", "sports", "games"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/900e6863-d3dd-4c88-8a05-bb343effc484/",
        source: "E-Pustakalaya",
      },
      {
        title: "गीतामा के छ? (Geetama Ke Chha?)",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890212",
        description: "आकारमा सानो भएर पनि पूर्वीय ज्ञानको महासागर मानिने श्रीमद्भगवद्गीताका प्रत्येक अध्यायको सारांश खिचेर यस गीतामा के छ पुस्तकमा त्यसको आशयसमेत सरल र सहजरूपमा प्रष्ट पार्ने प्रयत्न गरिएको छ।",
        category: "Religion",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2023,
        pages: 160,
        price: 380,
        totalCopies: 25,
        availableCopies: 20,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2023/10/31/गतम_क_छ.jpg",
        rating: 4.8,
        ratingCount: 280,
        borrowCount: 3025,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: true,
        tags: ["nepali", "geeta", "religion", "summary"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/f38902ad-3149-422b-8c4e-2f913fcd7e4c/",
        source: "E-Pustakalaya",
      },
      {
        title: "घुम्ने मेचमाथि अन्धो मान्छे",
        author: "भूपी शेरचन",
        isbn: "9789937890229",
        description: "यो कविता साझा प्रकाशनबाट प्रकाशित गरेको हो। यस कविता लेखक भूपी शेरचन हुन्। म पाँच वर्षको शिशु हुर्दा मेरी माताको निधन भएको थियो।",
        category: "Poetry",
        publisher: "साझा प्रकाशन",
        publishYear: 2020,
        pages: 80,
        price: 250,
        totalCopies: 20,
        availableCopies: 16,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/04/02/घमन_मचमथ_अनध_मनछ.jpg",
        rating: 4.6,
        ratingCount: 210,
        borrowCount: 569,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "poetry", "bhupi-sherchan"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/d047ff33-b5ae-4c86-9f75-19b9044f992d/",
        source: "E-Pustakalaya",
      },
      {
        title: "दोषी चश्मा (Doshi Chasma)",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890236",
        description: "सोह्र ओटा मौलिक मनोवैज्ञानिक कथाहरूको सङ्ग्रह।",
        category: "Fiction",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2022,
        pages: 200,
        price: 420,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2022/12/02/दष_चशम_सहर_ओट_मलक_मनवजञनक_कथ.jpg",
        rating: 4.4,
        ratingCount: 175,
        borrowCount: 815,
        badge: "New",
        isFeatured: false,
        isNewRelease: true,
        tags: ["nepali", "psychology", "stories", "fiction"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/0b2c9612-986c-4eb8-a44f-246bff0db8b4/",
        source: "E-Pustakalaya",
      },
      {
        title: "तुङदुङ्गे मुन्धुम - किरात आख्यान",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890243",
        description: "किरात आख्यान सम्बन्धी एक अध्ययन ग्रन्थ।",
        category: "History",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2024,
        pages: 250,
        price: 480,
        totalCopies: 12,
        availableCopies: 10,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2024/01/17/Tundunge_Mundhum.png",
        rating: 4.3,
        ratingCount: 95,
        borrowCount: 244,
        badge: "New",
        isFeatured: false,
        isNewRelease: true,
        tags: ["nepali", "kirat", "mundhum", "history"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/bea02ceb-8370-4d5e-ba2c-baa553a0acf8/",
        source: "E-Pustakalaya",
      },
      {
        title: "In the Loop: A Reference Guide to American English Idioms",
        author: "U.S. Department of State",
        isbn: "9780160831850",
        description: "A comprehensive guide to American English idioms with explanations and examples for English language learners.",
        category: "Self-Help",
        publisher: "U.S. Department of State",
        publishYear: 2008,
        pages: 220,
        price: 550,
        totalCopies: 10,
        availableCopies: 8,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/jCYlYfuC45mmJqx6WNtPRShn90xUeu.jpg",
        rating: 4.3,
        ratingCount: 160,
        borrowCount: 420,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["english", "idioms", "reference", "language-learning"],
        language: "English",
        sourceUrl: "https://pustakalaya.org/documents/detail/b02ccb2f-43b0-4ddc-bd50-6f8191a82dfd/",
        source: "E-Pustakalaya",
      },
      {
        title: "जलवायु परिवर्तन र चक्रीय अर्थतन्त्र",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890250",
        description: "जलवायु परिवर्तन र चक्रीय अर्थतन्त्र सम्बन्धी अभ्यास पुस्तिका।",
        category: "Science",
        publisher: "नेपाल सरकार",
        publishYear: 2024,
        pages: 120,
        price: 300,
        totalCopies: 25,
        availableCopies: 20,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2024/12/13/जलवय_परवरतन_र_चकरय_अरथतनतर_अभयस_पसतक.jpg",
        rating: 4.2,
        ratingCount: 75,
        borrowCount: 180,
        badge: "New",
        isFeatured: true,
        isNewRelease: true,
        tags: ["nepali", "climate-change", "economy", "environment"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/dfe27aa8-10d8-48d7-af5c-28f1debee801/",
        source: "E-Pustakalaya",
      },
      {
        title: "जलवायु परिवर्तन र कृषि",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890267",
        description: "जलवायु परिवर्तन र कृषि सम्बन्धी किसानका लागि सहयोगी पुस्तिका।",
        category: "Science",
        publisher: "नेपाल सरकार",
        publishYear: 2024,
        pages: 100,
        price: 280,
        totalCopies: 30,
        availableCopies: 25,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/TUTgmYM8qUx5N4nsRPbMbb6dcjRfZi.gif",
        rating: 4.3,
        ratingCount: 85,
        borrowCount: 220,
        badge: "New",
        isFeatured: true,
        isNewRelease: true,
        tags: ["nepali", "climate-change", "agriculture", "farmers"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/3cc8a86f-a7c1-41ad-a5a1-6b76521c88d9/",
        source: "E-Pustakalaya",
      },
      {
        title: "यो-यो यती हावामा उड्न थाल्यो!",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890274",
        description: "बालबालिकाका लागि तयार पारिएको रमाइलो र शिक्षाप्रद पुस्तक।",
        category: "Children",
        publisher: "OLE Nepal",
        publishYear: 2020,
        pages: 28,
        price: 160,
        totalCopies: 35,
        availableCopies: 28,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/R8TO2eGp3MokQ5E2jozD0cj0OCfyBn.jpg",
        rating: 4.5,
        ratingCount: 140,
        borrowCount: 680,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "children", "fun", "learning"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/99319df7-0a90-40cc-8103-ed85fcb30c16/",
        source: "E-Pustakalaya",
      },
      {
        title: "सोह्रौं योजना (आर्थिक वर्ष २०८१/८२-२०८५/८६)",
        author: "राष्ट्रिय योजना आयोग",
        isbn: "9789937890281",
        description: "नेपालको सोह्रौं योजनाको अवधारणा-पत्र। राष्ट्रिय योजना आयोगको मिति २०८०/०४/१७ को बैठकबाट स्वीकृत।",
        category: "Business",
        publisher: "राष्ट्रिय योजना आयोग, नेपाल",
        publishYear: 2024,
        pages: 350,
        price: 500,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2024/07/16/सहर_यजन_आरथक_वरष_२०८१८२२०८५८६.jpg",
        rating: 4.1,
        ratingCount: 65,
        borrowCount: 446,
        badge: "New",
        isFeatured: false,
        isNewRelease: true,
        tags: ["nepali", "policy", "government", "planning"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/91788673-b552-4a97-aa4d-c2547b62bae0/",
        source: "E-Pustakalaya",
      },
      {
        title: "चम्पा (Champa - Novel)",
        author: "विश्वेश्वरप्रसाद कोइराला",
        isbn: "9789937890298",
        description: "नेपाली सामाजिक उपन्यास। बीपी कोइरालाद्वारा लिखित प्रसिद्ध सामाजिक उपन्यास।",
        category: "Fiction",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2020,
        pages: 280,
        price: 480,
        totalCopies: 20,
        availableCopies: 16,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/09/30/चमप_नपल_समजक_उपनयस.jpg",
        rating: 4.5,
        ratingCount: 320,
        borrowCount: 2800,
        badge: "Popular",
        isFeatured: true,
        isNewRelease: false,
        tags: ["nepali", "novel", "bp-koirala", "social"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/35ad27c7-628a-4218-ae44-9fc977b1d035/",
        source: "E-Pustakalaya",
      },
      {
        title: "शाकुन्तल (Shakuntal - Epic)",
        author: "विश्वेश्वरप्रसाद कोइराला",
        isbn: "9789937890304",
        description: "महाकाव्य शाकुन्तल बीपी कोइरालाद्वारा लिखित प्रसिद्ध महाकाव्य।",
        category: "Poetry",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2020,
        pages: 180,
        price: 400,
        totalCopies: 18,
        availableCopies: 14,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/09/30/शकनतल_महकवय.jpg",
        rating: 4.4,
        ratingCount: 260,
        borrowCount: 2100,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "epic", "bp-koirala", "poetry"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/bedaab73-cca1-4181-9385-94e7690e4251/",
        source: "E-Pustakalaya",
      },
      {
        title: "'९७ साल ('97 Sal)",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890311",
        description: "नेपालको इतिहासमा ९७ सालको महत्त्वपूर्ण घटनाहरूको वर्णन।",
        category: "History",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2020,
        pages: 220,
        price: 450,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/xm77Zolg7tZhqtroVCWRNCWhjLXvKx.jpg",
        rating: 4.3,
        ratingCount: 180,
        borrowCount: 1500,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "history", "97-sal", "political"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/fda7a2ab-cf13-4f46-85b3-b978f4a5c245/",
        source: "E-Pustakalaya",
      },
      {
        title: "इतिहासका विम्बहरू",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890328",
        description: "नेपालको इतिहासका विभिन्न पक्षहरूको अध्ययन र विश्लेषण।",
        category: "History",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2020,
        pages: 260,
        price: 480,
        totalCopies: 12,
        availableCopies: 10,
        coverImage: "https://pustakalaya.org/media/uploads/thumbnails/document/2020/05/04/इतहसक_वमबहर.jpg",
        rating: 4.2,
        ratingCount: 140,
        borrowCount: 1200,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "history", "analysis"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/2519b618-51fa-4725-b833-cdb95f85880e/",
        source: "E-Pustakalaya",
      },
      {
        title: "इन्द्रकिल पहाडसँग",
        author: "विभिन्न लेखकहरू",
        isbn: "9789937890335",
        description: "नेपालको पहाडी जीवन र संस्कृतिको वर्णन।",
        category: "Fiction",
        publisher: "नेपाल प्रकाशन",
        publishYear: 2020,
        pages: 180,
        price: 380,
        totalCopies: 15,
        availableCopies: 12,
        coverImage: "https://pustakalaya.org/media/uploads/op/thumbnail/6BMt5mX8gNhmQJu8FQIptgrWuygGl3.gif",
        rating: 4.3,
        ratingCount: 110,
        borrowCount: 900,
        badge: "",
        isFeatured: false,
        isNewRelease: false,
        tags: ["nepali", "mountain", "culture", "fiction"],
        language: "Nepali",
        sourceUrl: "https://pustakalaya.org/documents/detail/f2afbef0-2d44-4c1f-ab86-d357a8eb1144/",
        source: "E-Pustakalaya",
      },
    ];

    const existingBooks = await Book.find({ source: "E-Pustakalaya" });
    if (existingBooks.length > 0) {
      return res.json({
        success: false,
        message: `E-Pustakalaya books already exist (${existingBooks.length} books). Delete them first or use the update endpoint.`,
      });
    }

    const createdBooks = await Book.insertMany(books);

    res.json({
      success: true,
      message: `Seeded ${createdBooks.length} books from E-Pustakalaya`,
      booksAdded: createdBooks.length,
      books: createdBooks.map((b) => ({
        title: b.title,
        author: b.author,
        category: b.category,
        language: b.language,
        sourceUrl: b.sourceUrl,
      })),
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Failed to seed E-Pustakalaya books",
      error: error.message,
    });
  }
}

export async function updateBookWithPustakalayaUrl(req, res) {
  try {
    const { id } = req.params;
    const { sourceUrl } = req.body;

    const book = await Book.findByIdAndUpdate(
      id,
      { sourceUrl, source: "E-Pustakalaya" },
      { new: true }
    );

    if (!book) {
      return res.status(404).json({ success: false, message: "Book not found" });
    }

    res.json({ success: true, book });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: "Failed to update book",
      error: error.message,
    });
  }
}
